ROUTE_NAME_PREFIX = "asgi_admin"
ROUTE_NAME_SEPARATOR = ":"
SCOPE_ROOT_VIEW = "_asgi_root_view"
SCOPE_CURRENT_VIEW_KEY = "_asgi_admin_current_view"
SCOPE_CURRENT_ROUTE_KEY = "_asgi_admin_current_route"
CONTEXT_ROOT_VIEW = SCOPE_ROOT_VIEW
CONTEXT_CURRENT_VIEW_KEY = SCOPE_CURRENT_VIEW_KEY
CONTEXT_CURRENT_ROUTE_KEY = SCOPE_CURRENT_ROUTE_KEY

__all__ = [
    "ROUTE_NAME_PREFIX",
    "ROUTE_NAME_SEPARATOR",
    "SCOPE_ROOT_VIEW",
    "SCOPE_CURRENT_VIEW_KEY",
    "SCOPE_CURRENT_ROUTE_KEY",
    "CONTEXT_ROOT_VIEW",
    "CONTEXT_CURRENT_VIEW_KEY",
    "CONTEXT_CURRENT_ROUTE_KEY",
]
