ROUTE_NAME_PREFIX = "asgi_admin."
SCOPE_NAVIGATION_KEY = "_asgi_admin_navigation"
SCOPE_TITLE_KEY = "_asgi_admin_title"
CONTEXT_NAVIGATION_KEY = SCOPE_NAVIGATION_KEY
CONTEXT_TITLE_KEY = SCOPE_TITLE_KEY
CONTEXT_CURRENT_ROUTE_KEY = "_asgi_admin_current_route"

__all__ = [
    "ROUTE_NAME_PREFIX",
    "SCOPE_NAVIGATION_KEY",
    "SCOPE_TITLE_KEY",
    "CONTEXT_NAVIGATION_KEY",
    "CONTEXT_TITLE_KEY",
    "CONTEXT_CURRENT_ROUTE_KEY",
]
